language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: npm
  email: jason.p.pickering@gmail.com
  api_key:
    secure: FLoUUEZAE/8xvfoC7DOF6AWU/IprS/cohQuBCc60SRPOZw3Ea+ziNqySM2Z9ZADcabm5yU6sNvYG90vKF5FinVtv4s2l+fpWQ5UFCi5iLW5cVeSUhmD/Id61Rep9pZCnxx3PyVW7wO20apQqrXVkaikqXE6M4P9lHEvlQcAS2L96DQhwNBSmGjD+M0jCzxjFGSfK4rYRIEuJiNjgf505iZlZg4XAaXvv3UAjP2Bq+vAOyOrZ39oR1b68QTGxf7Z/OnUl5Edfh5NaymSIrhrUicE0jgDBknwq9ZhOp0AWqrUCdH56sYc8c7MR+ZgauuUai8Y3lauicuVPBSfFWvadwjZTlxb2wVY3Jx2MCBn2AXGw7aJUw7iQrRuEg7dQNfMa/6FcsOQ/i8ZGdjrV40tzp52wCTnDc9rOfKUIMoXI9x53qLLA/M8CGm68WCE/BlwrM2VMsts3K3ihSjKF+G7QmZOIF1GSucsysLJ9AA/nbh/Wl6MqkrCPb5lrJwsx3LSfw7ttjvt9RrsTDSPvxWL4soxYNnz68rxRBWjQ6ZVJBvSgCzL7ABNawqP9UbCa42y8Jz/iZ9k+iKvuCpnJs4bhmlBRBzcsA8Uq85nv4fPSMtTt6o5R+L1Zwl/PYWW5WSNfZC/qs6chLfHHSBRNsj2uWQinwlW++6BvkRmg/0c4yLA=
  on:
    tags: true
    repo: dhis2/d2-tracker
notifications:
  slack:
    secure: vq9UQ3Hu1d6bbrotmK3ROs9FcVRxKxjXEg8q+GIXdIcEVSfvnrrne8FBv7JkuSD9RnQvmMxpqyE9+WYL+8ImVB6PKB5VyFokz185Lus0JXKt9u3nZTnN01xtHwvfMyY8dB3Nx8v0IFwx8D9/Uqd4x2hish45pkJkhqevj2OsoIR06zDGlpSlrbwMOVGafMdXxPpwVbDqjbwdMmfOZ4hkQGnYu+CuYzINJ06Xgp5ejiL42OKnWvT17OOmNDt5lP8cvGS1WT7wMMPik3WmEsGgxWzWMNKUO/wZSC1O4We1OatqB7mHmDUxfHfgbAx4RnW5QuTynfcDvL51rAy+yNBwSM+6TC82Q8zHameWPc7cE8YztQUJ4ZS2XuGFq85mBBSXDxzvFk7Rb5JY5GvL/5BL5Qy6/YMGpy0cJmwyUutzkXsMTLSiQJPqaQ6F1tOaUYFcgcDEKkpSldGohmNXcbBMPoZMsBL2+066a9/ojwitlzWeLGYJsvKPvZdm236nMLn/zflNcmevTMqyyL1B/HRcGol2iulDSKw/ddfBLQKwsVYUbGV4QSq5iZSudeSdFx3ZZgAMzHUcBTfNG1XiTQl0tk7NgaMvEe5Q7smYcE0BvLRmXUsM+MAupdkltIc17vahD8aZzif5uwsTG3itGcGUHDqWx+5Z0M/VgyjxNldvQwE=
