language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: npm
  email: jason.p.pickering@gmail.com
  api_key:
    secure: jZPlweJQmoKAekDhbj+mjjaoP96AmLQK2CwUlEJUnmjoFxiJ9zrxAlp0f8Mo5AeQL5MXjU5/gc4exK6jBwAT7AFCOUts1M5ophC+hrLryZIHZyFH8fB0BuY42/BrhxH72eKQGQpjY5bIDNVTwRqNeyOl9bTAAVffENiBrDjG8TwXcfTa3u6ABzqC5nZtCcz3+8kq5SSt4968+pdGUg7kQ4fYNy7sJTbcZo6H3n91HPSmAnC3i8MVsWJiFpVNL2buZLK8Oi8kgfsk5PFhYR/J4+hSJpiRH9Ez9S7+FdmwlH25Sl8fFuMJrDQRQSkBh6ckGKAFrNC3O4gllyof2Bgy1Ruy4pumHVXGcQZQZPXo7+D5IjE3nU6HLKOhpFhkOnIxYbuq1ewF4ZOOd8JpOpkuMvwdF+5cXM7REyoLStM3BOD4RQMP6N0hIEM7U4LSDcO1Gh4NcQa20KcH1/XszMLaAPkhdGxOMmnXxO4KqOdChUufVqW4dTm3mQoFrU3H5UpHvYksNe01/POe2HaUVCwVlIZMZ4mLqvV6FnTUXuFjM5gP3mUZCyDcwUhur8C1+//2YL/F3KHmqxXcbB0wwXpfM4kTavq5fXZWCXEFV6qj8gR7ptper5nSQLDjeOYPPwjN8UBE7rmv4a0MlOzXGl6nKvylYOqNybukpZKUVcuj5rY=
  on:
    tags: true
    repo: dhis2/d2-tracker
notifications:
  slack:
    secure: vq9UQ3Hu1d6bbrotmK3ROs9FcVRxKxjXEg8q+GIXdIcEVSfvnrrne8FBv7JkuSD9RnQvmMxpqyE9+WYL+8ImVB6PKB5VyFokz185Lus0JXKt9u3nZTnN01xtHwvfMyY8dB3Nx8v0IFwx8D9/Uqd4x2hish45pkJkhqevj2OsoIR06zDGlpSlrbwMOVGafMdXxPpwVbDqjbwdMmfOZ4hkQGnYu+CuYzINJ06Xgp5ejiL42OKnWvT17OOmNDt5lP8cvGS1WT7wMMPik3WmEsGgxWzWMNKUO/wZSC1O4We1OatqB7mHmDUxfHfgbAx4RnW5QuTynfcDvL51rAy+yNBwSM+6TC82Q8zHameWPc7cE8YztQUJ4ZS2XuGFq85mBBSXDxzvFk7Rb5JY5GvL/5BL5Qy6/YMGpy0cJmwyUutzkXsMTLSiQJPqaQ6F1tOaUYFcgcDEKkpSldGohmNXcbBMPoZMsBL2+066a9/ojwitlzWeLGYJsvKPvZdm236nMLn/zflNcmevTMqyyL1B/HRcGol2iulDSKw/ddfBLQKwsVYUbGV4QSq5iZSudeSdFx3ZZgAMzHUcBTfNG1XiTQl0tk7NgaMvEe5Q7smYcE0BvLRmXUsM+MAupdkltIc17vahD8aZzif5uwsTG3itGcGUHDqWx+5Z0M/VgyjxNldvQwE=
